# frozen_string_literal: true

# =============================================================================
# COMMENTS CONTROLLER — api/v1/comments_controller.rb
# =============================================================================
#
# Manages polymorphic Comments on both Projects and Tasks.
#
# ROUTES (generated by `resources :comments` nested inside both :projects and :tasks):
#   GET    /api/v1/projects/:project_id/comments  → index (project comments)
#   POST   /api/v1/projects/:project_id/comments  → create (comment on project)
#   GET    /api/v1/tasks/:task_id/comments         → index (task comments)
#   POST   /api/v1/tasks/:task_id/comments         → create (comment on task)
#   DELETE /api/v1/comments/:id                    → destroy (shallow)
#
# POLYMORPHIC ROUTING:
#   The controller detects which type of commentable parent we're dealing with
#   by checking which params key is present (`:project_id` vs `:task_id`).
#   The `find_commentable` private method handles this dispatching.
#
# POLYMORPHIC DATABASE INSERT:
#   When we call `@commentable.comments.create!(...)`, Rails automatically sets:
#     commentable_type = "Project" (or "Task")
#     commentable_id   = @commentable.id
#   We never need to set these manually — the association handles it.
# =============================================================================

module Api
  module V1
    class CommentsController < ApplicationController
      # =========================================================================
      # BEFORE ACTIONS
      # =========================================================================
      before_action :find_commentable, only: %i[index create]
      before_action :find_comment, only: %i[destroy]

      # =========================================================================
      # GET /api/v1/projects/:project_id/comments
      # GET /api/v1/tasks/:task_id/comments
      # =========================================================================
      # Returns all comments for the parent resource.
      # Ordered newest-first. Includes the author (user) for each comment.
      # =========================================================================
      def index
        authorize! :read, Comment

        # `@commentable.comments` generates:
        #   SELECT * FROM comments
        #   WHERE commentable_type = 'Project' AND commentable_id = :id
        # (or 'Task') — completely automatic via the polymorphic association.
        @comments = @commentable.comments
                                .includes(:user)
                                .recent

        render_success({ comments: @comments.map { |c| CommentSerializer.new(c) },
                         total: @comments.count })
      end

      # =========================================================================
      # POST /api/v1/projects/:project_id/comments
      # POST /api/v1/tasks/:task_id/comments
      # =========================================================================
      # Creates a new comment on the commentable parent.
      #
      # Request body:
      #   { "comment": { "body": "This looks great!" } }
      #
      # The user and commentable are set server-side (NOT from params) to prevent:
      #   - Commenting as another user (user_id tampering)
      #   - Attaching comment to wrong parent (commentable_id tampering)
      # =========================================================================
      def create
        @comment = @commentable.comments.build(comment_params)
        @comment.user = current_user  # Always set author from authenticated user

        # Ability: can :create, Comment → any authenticated member
        authorize! :create, @comment

        if @comment.save
          render_success(CommentSerializer.new(@comment), :created)
        else
          render_error("comment_creation_failed", @comment.errors.full_messages, :unprocessable_entity)
        end
      end

      # =========================================================================
      # DELETE /api/v1/comments/:id
      # =========================================================================
      # Only the comment author (or an admin) can delete a comment.
      # Ability: can :destroy, Comment, user_id: user.id
      # =========================================================================
      def destroy
        # authorize! checks: @comment.user_id == current_user.id OR admin?
        authorize! :destroy, @comment

        @comment.destroy!
        render_success({ message: "Comment deleted." })
      end

      private

      # =========================================================================
      # POLYMORPHIC PARENT RESOLUTION
      # =========================================================================
      # Determines the parent resource (Project or Task) from route params.
      # This pattern allows a SINGLE controller to handle comments for multiple
      # parent models without duplicating code.
      #
      # How it works:
      #   - Routes pass :project_id when commenting on a project
      #   - Routes pass :task_id when commenting on a task
      #   - We check which param is present to find the right parent
      #
      # The result @commentable is a Project or Task instance.
      # Calling @commentable.comments.create! then sets:
      #   commentable_type = "Project" (or "Task") automatically.
      # =========================================================================
      def find_commentable
        if params[:project_id]
          @commentable = Project.find(params[:project_id])
        elsif params[:task_id]
          @commentable = Task.find(params[:task_id])
        else
          render_error("commentable_not_found", ["Parent resource not specified"], :bad_request)
        end
      end

      def find_comment
        @comment = Comment.find(params[:id])
      end

      # =========================================================================
      # STRONG PARAMETERS
      # =========================================================================
      # Only `body` is permitted — user_id and commentable_* are set server-side.
      # =========================================================================
      def comment_params
        params.require(:comment).permit(:body)
      end
    end
  end
end
